version: '3.5'

services:

  web:
    build:
      context: ../../..
      dockerfile: deployment/docker/web/web.Dockerfile
    container_name: falconclean.web
    ports:
      - 80:80
      - 443:443
    volumes:
        - ../../../code/web:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUSH_PUBLIC_KEY=${PUSH_PUBLIC_KEY}
      - PUSH_PRIVATE_KEY=${PUSH_PRIVATE_KEY}
    restart: always
    networks:
      - default


  db:
    image: "mysql"
    container_name: falconclean.db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "../../../db/webdb/data/mysql/:/var/lib/mysql/"
      - "../../../code/db/:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=falconclean
    restart: always
    networks:
      - default


networks:
  default:
    name: falconclean.default